<?php

namespace AppBundle\Repository;

/**
 * DrinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrinkRepository extends \Doctrine\ORM\EntityRepository
{
}
